<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "abexto_schemaorg_breadcrumb"
 *
 * Auto generated by Extension Builder 2019-06-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Abexto Schema.Org Breadcrumbs',
    'description' => 'Generates http://schema.org/BreadcrumbList data for pages in JSON-LD format',
    'category' => 'misc',
    'author' => 'Andreas Prucha',
    'author_email' => 'andreas.prucha@gmail.com',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 1,
    'version' => '0.0.2',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.99.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
